sylius_sitemap_index:
    path: /sitemap_index.xml
    methods: [GET]
    defaults:
        _controller: sylius.controller.sitemap_index:showAction

sylius_sitemap_no_index:
    path: /sitemap.xml
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sylius_sitemap_index
        permanent: true

sylius_sitemap_providers:
    resource: .
    type: sitemap
