sylius_sitemap_all:
    path: /sitemap/all.{_format}
    methods: [GET]
    defaults:
        _controller: sylius.controller.sitemap:showAction
        _format: xml
    requirements:
        _format: xml

sylius_sitemap_providers:
    resource: .
    type: sitemap
